// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DateTimeStyleController from "./date_time_style_controller"
application.register("date-time-style", DateTimeStyleController)

import SelectAndGoController from "./select_and_go_controller"
application.register("select-and-go", SelectAndGoController)
